name: SinhalaStoryBot Auto Run

on:

  workflow_dispatch:

  schedule:
    # GitHub uses UTC time
    # Runs 5 times per day
    - cron: "30 1 * * *"
    - cron: "30 4 * * *"
    - cron: "30 7 * * *"
    - cron: "30 10 * * *"
    - cron: "30 13 * * *"


jobs:

  create-videos:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg


    - name: Install Python Libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Create Required Folders
      run: |
        mkdir -p output/videos
        mkdir -p output/images
        mkdir -p output/audio
        mkdir -p output/temp
        mkdir -p logs
        mkdir -p database


    - name: Run SinhalaStoryBot
      run: |
        python run.py


    - name: Check Generated Files
      if: always()
      run: |
        echo "========== OUTPUT CHECK =========="
        ls -R output || true
        echo "=================================="


    - name: Upload Generated Videos
      if: always()
      uses: actions/upload-artifact@v4
      with:

        name: sinhala-story-videos

        path: output/

        retention-days: 7
